# Generated by Django 3.2.8 on 2021-10-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trend',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
