# Generated by Django 3.2.8 on 2021-11-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20211105_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='marcket_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
